#[[
# @file naca0012.toml
# @brief The config file SubrosaDG example naca0012.
#
# @author Yufei.Liu, Calm.Liu@outlook.com | Chenyu.Bao, bcynuaa@163.com
# @date 2022-04-17
#
# @version 0.1.0
# @copyright Copyright (c) 2022 - 2023 by SubrosaDG developers. All rights reserved.
# SubrosaDG is free software and is distributed under the MIT license.
#]]

Dimension = 2

PolynomialOrder = 3

SimulationType = "Euler"

NoVisFluxType = "Roe"

MeshFile = "build/out/naca0012/mesh/naca0012.msh"

[TimeIntegration]
type = "RungeKutta3"
iteration = 1000
CFL = 0.1  # < 1 / ( 2 * p + 1 )
tolerance = -8  # log10

[Boundary]
name = ["bc-1", "bc-2"]

[BoundaryCondition.bc-1]
type = "Farfield"

[BoundaryCondition.bc-2]
type = "Wall"

[ThermodynamicModel]
EquationOfState = "IdealGas"
gamma = 1.4
c_p = 1.0  # dimensionless e to \bar { e } = 1 - 1 / gamma
R = 0.7142857142857143  # 1.0 / 1.4

[Region]
name = ["vc-1"]

[InitialParameter.vc-1]
U = [0.7998096216639273, 0.017451908027648896, 0.0]  # Ma = 0.8, alpha = 1.25
rho = 1.4
p = 1.0
T = 1.0

[FarfieldParameter]
U = [0.7998096216639273, 0.017451908027648896, 0.0]  # Ma = 0.8, alpha = 1.25
rho = 1.4
p = 1.0
T = 1.0
